# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2016-10-11 16:52+0200\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=CHARSET\n"
"Content-Transfer-Encoding: 8bit\n"

#: ../gecosws_config_assistant/controller/AutoSetupController.py:108
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:114
msgid "The URL field is empty!"
msgstr ""

#: ../gecosws_config_assistant/controller/AutoSetupController.py:108
#: ../gecosws_config_assistant/controller/AutoSetupController.py:184
#: ../gecosws_config_assistant/controller/AutoSetupController.py:192
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:114
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:129
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:137
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:216
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:248
#: ../gecosws_config_assistant/controller/LocalUserController.py:81
#: ../gecosws_config_assistant/controller/LocalUserController.py:97
#: ../gecosws_config_assistant/controller/LocalUserController.py:106
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:373
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:388
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:408
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:434
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:443
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:452
#: ../gecosws_config_assistant/view/LocalUserElemDialog.py:123
#: ../gecosws_config_assistant/view/LocalUserElemView.py:156
msgid "Please fill all the mandatory fields."
msgstr ""

#: ../gecosws_config_assistant/controller/AutoSetupController.py:115
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:121
msgid "Malformed URL in URL field!"
msgstr ""

#: ../gecosws_config_assistant/controller/AutoSetupController.py:115
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:121
msgid "Please double-check it."
msgstr ""

#: ../gecosws_config_assistant/controller/AutoSetupController.py:134
#: ../gecosws_config_assistant/controller/AutoSetupController.py:164
#: ../gecosws_config_assistant/controller/AutoSetupController.py:173
#: ../gecosws_config_assistant/controller/AutoSetupController.py:200
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:156
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:186
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:195
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:203
msgid "Can't connect to GECOS CC!"
msgstr ""

#: ../gecosws_config_assistant/controller/AutoSetupController.py:134
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:156
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:454
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:581
msgid "The server HTTPS certificate is expired!"
msgstr ""

#: ../gecosws_config_assistant/controller/AutoSetupController.py:141
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:163
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:461
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:588
msgid "The certificate of this server is not trusted!"
msgstr ""

#: ../gecosws_config_assistant/controller/AutoSetupController.py:142
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:164
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:462
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:589
msgid "Do you wan't to add it to the trusted certificates list?"
msgstr ""

#: ../gecosws_config_assistant/controller/AutoSetupController.py:144
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:166
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:464
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:591
msgid "Subject:"
msgstr ""

#: ../gecosws_config_assistant/controller/AutoSetupController.py:145
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:167
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:465
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:592
msgid "Issuer:"
msgstr ""

#: ../gecosws_config_assistant/controller/AutoSetupController.py:146
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:168
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:466
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:593
msgid "Serial Number:"
msgstr ""

#: ../gecosws_config_assistant/controller/AutoSetupController.py:147
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:169
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:467
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:594
msgid "Not before:"
msgstr ""

#: ../gecosws_config_assistant/controller/AutoSetupController.py:147
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:169
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:467
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:594
msgid "Not after:"
msgstr ""

#: ../gecosws_config_assistant/controller/AutoSetupController.py:164
#: ../gecosws_config_assistant/controller/AutoSetupController.py:173
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:186
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:195
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:489
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:500
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:616
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:627
msgid "SSL ERROR:"
msgstr ""

#: ../gecosws_config_assistant/controller/AutoSetupController.py:184
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:129
msgid "The Username field is empty!"
msgstr ""

#: ../gecosws_config_assistant/controller/AutoSetupController.py:192
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:137
msgid "The Password field is empty!"
msgstr ""

#: ../gecosws_config_assistant/controller/AutoSetupController.py:200
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:203
msgid "Please double-check all the data and your network setup."
msgstr ""

#: ../gecosws_config_assistant/controller/AutoSetupController.py:222
msgid "Please wait"
msgstr ""

#: ../gecosws_config_assistant/controller/AutoSetupController.py:232
msgid "Error getting data"
msgstr ""

#: ../gecosws_config_assistant/controller/AutoSetupController.py:233
msgid "Can't read auto setup configuration data from GECOS Control Center!"
msgstr ""

#: ../gecosws_config_assistant/controller/AutoSetupController.py:238
msgid "Success getting data from GECOS server"
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:216
msgid "The GECOS workstation name field is empty!"
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:235
msgid "The GECOS workstation name already exist!"
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:235
msgid "Please choose a different name."
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:248
msgid "You must select an OU!"
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:345
#: ../gecosws_config_assistant/view/GecosCCSetupProcessView.py:85
msgid "Link to Chef"
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:346
msgid "Register in GECOS CC"
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:351
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:374
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:384
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:539
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:694
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:724
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:747
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:756
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:766
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:776
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:841
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:854
msgid "IN PROCESS"
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:355
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:361
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:367
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:377
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:404
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:414
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:472
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:487
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:498
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:513
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:526
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:599
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:614
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:625
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:643
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:658
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:681
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:703
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:713
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:749
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:759
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:785
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:798
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:807
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:818
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:827
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:844
#: ../gecosws_config_assistant/view/GecosCCSetupProcessView.py:134
#: ../gecosws_config_assistant/view/GecosCCSetupProcessView.py:139
#: ../gecosws_config_assistant/view/GecosCCSetupProcessView.py:144
#: ../gecosws_config_assistant/view/GecosCCSetupProcessView.py:153
#: ../gecosws_config_assistant/view/GecosCCSetupProcessView.py:163
#: ../gecosws_config_assistant/view/GecosCCSetupProcessView.py:168
#: ../gecosws_config_assistant/view/GecosCCSetupProgressView.py:106
#: ../gecosws_config_assistant/view/GecosCCSetupProgressView.py:111
#: ../gecosws_config_assistant/view/GecosCCSetupProgressView.py:116
#: ../gecosws_config_assistant/view/GecosCCSetupProgressView.py:125
#: ../gecosws_config_assistant/view/GecosCCSetupProgressView.py:134
#: ../gecosws_config_assistant/view/GecosCCSetupProgressView.py:139
msgid "ERROR"
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:371
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:381
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:536
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:691
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:721
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:729
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:753
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:763
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:773
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:838
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:851
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:860
msgid "DONE"
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:406
msgid "There was an error while getting the client certificate"
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:416
msgid "There was an error while saving the client certificate"
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:454
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:489
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:500
msgid "Can't connect to GEMs repository!"
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:515
msgid "There was an error while adding the GEMs repository:\n"
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:528
msgid "There was an error while installing a required GEM: "
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:581
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:616
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:627
msgid "Can't connect to Chef Server!"
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:645
msgid "Can't create/modify /etc/chef/client.rb file"
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:660
msgid "Can't link to chef server!"
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:683
msgid "Can't create/modify /etc/chef.control file"
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:705
msgid "Can't register the computer in GECOS CC"
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:715
msgid "Can't save /etc/gcc.control file"
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:741
msgid "Unlink from Chef"
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:742
msgid "Unregister from GECOS CC"
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:787
msgid "Can't unregister the computer from GECOS CC"
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:800
msgid "Can't remove /etc/chef.control file"
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:809
msgid "Can't remove /etc/chef/client.pem file"
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:820
msgid "Can't delete Chef node"
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:829
msgid "Can't remove /usr/bin/chef-client-wrapper file"
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:846
msgid "Can't remove /etc/gcc.control file"
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:880
msgid "Can't get OUs from GECOS Control Center"
msgstr ""

#: ../gecosws_config_assistant/controller/LocalUserController.py:81
msgid "The login field is empty!"
msgstr ""

#: ../gecosws_config_assistant/controller/LocalUserController.py:88
msgid "The login field contains not allowed characters!"
msgstr ""

#: ../gecosws_config_assistant/controller/LocalUserController.py:97
msgid "The name field is empty!"
msgstr ""

#: ../gecosws_config_assistant/controller/LocalUserController.py:106
msgid "The password field is empty!"
msgstr ""

#: ../gecosws_config_assistant/controller/LocalUserController.py:114
msgid "The password field contains not allowed characters."
msgstr ""

#: ../gecosws_config_assistant/controller/LocalUserController.py:165
msgid "Do you really want to delete this user? "
msgstr ""

#: ../gecosws_config_assistant/controller/MainMenuController.py:181
msgid "The system has a network connection configured"
msgstr ""

#: ../gecosws_config_assistant/controller/MainMenuController.py:183
msgid "The system has NO network connection"
msgstr ""

#: ../gecosws_config_assistant/controller/MainMenuController.py:186
msgid "The system has loaded setup data values from GECOS server"
msgstr ""

#: ../gecosws_config_assistant/controller/MainMenuController.py:188
msgid "The system may load setup data values from GECOS server"
msgstr ""

#: ../gecosws_config_assistant/controller/MainMenuController.py:191
msgid "The system is synchronized with a NTP server"
msgstr ""

#: ../gecosws_config_assistant/controller/MainMenuController.py:193
msgid "The system is NOT synchronized with a NTP server"
msgstr ""

#: ../gecosws_config_assistant/controller/MainMenuController.py:196
msgid "The system is linked to a GECOS server"
msgstr ""

#: ../gecosws_config_assistant/controller/MainMenuController.py:198
msgid "The system is NOT linked to a GECOS server"
msgstr ""

#: ../gecosws_config_assistant/controller/MainMenuController.py:200
#, python-format
msgid "Users authenticate by %s method"
msgstr ""

#: ../gecosws_config_assistant/controller/MainMenuController.py:205
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:236
#: ../gecosws_config_assistant/dto/LDAPAuthMethod.py:43
#: ../gecosws_config_assistant/tests/dto/LDAPAuthMethodTest.py:40
#: ../gecosws_config_assistant/view/UserAuthDialog.py:66
#: ../gecosws_config_assistant/view/UserAuthDialog.py:147
#: ../gecosws_config_assistant/view/UserAuthDialog.py:189
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:101
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:296
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:314
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:334
msgid "LDAP"
msgstr ""

#: ../gecosws_config_assistant/controller/MainMenuController.py:207
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:238
#: ../gecosws_config_assistant/dto/ADAuthMethod.py:44
#: ../gecosws_config_assistant/tests/dto/ADAuthMethodTest.py:40
#: ../gecosws_config_assistant/view/UserAuthDialog.py:66
#: ../gecosws_config_assistant/view/UserAuthDialog.py:149
#: ../gecosws_config_assistant/view/UserAuthDialog.py:191
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:101
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:298
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:311
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:345
msgid "Active Directory"
msgstr ""

#: ../gecosws_config_assistant/controller/MainMenuController.py:209
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:234
#: ../gecosws_config_assistant/dto/LocalUsersAuthMethod.py:43
#: ../gecosws_config_assistant/tests/dto/LocalUsersAuthMethodTest.py:39
#: ../gecosws_config_assistant/view/UserAuthDialog.py:66
#: ../gecosws_config_assistant/view/UserAuthDialog.py:145
#: ../gecosws_config_assistant/view/UserAuthDialog.py:187
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:99
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:101
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:317
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:323
msgid "Internal"
msgstr ""

#: ../gecosws_config_assistant/controller/MainMenuController.py:272
msgid "Are you sure you want to update the GECOS Config Assistant?"
msgstr ""

#: ../gecosws_config_assistant/controller/MainMenuController.py:275
#: ../gecosws_config_assistant/controller/MainMenuController.py:283
msgid "An error occurred during the upgrade"
msgstr ""

#: ../gecosws_config_assistant/controller/MainMenuController.py:279
msgid "CGA is already at the newest version!"
msgstr ""

#: ../gecosws_config_assistant/controller/MainMenuController.py:281
msgid "GECOS Config Assistant has been udpated. Please restart GCA"
msgstr ""

#: ../gecosws_config_assistant/controller/NTPServerController.py:87
#: ../gecosws_config_assistant/controller/NTPServerController.py:91
msgid "Error saving NTP server data."
msgstr ""

#: ../gecosws_config_assistant/controller/NTPServerController.py:87
#: ../gecosws_config_assistant/controller/NTPServerController.py:91
#: ../gecosws_config_assistant/view/UserAuthDialog.py:408
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:378
msgid "See log for more details."
msgstr ""

#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:308
msgid ""
"The user authentication data has changed.\n"
"Do you want to setup the user authentication method using this new data?"
msgstr ""

#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:373
msgid "The URI field is empty!"
msgstr ""

#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:380
msgid "Malformed LDAP URI!"
msgstr ""

#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:380
msgid "Please check that the URI starts with 'ldap://' or 'ldaps://'."
msgstr ""

#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:388
msgid "The users base DN field is empty!"
msgstr ""

#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:395
msgid "Can't connect to LDAP server!"
msgstr ""

#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:395
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:460
msgid "Please check all the fields and your network connection."
msgstr ""

#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:408
msgid "The Domain field is empty!"
msgstr ""

#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:425
msgid "Can't resolv the Active Directory Domain name!"
msgstr ""

#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:426
msgid "Please check the Domain field and your DNS configuration."
msgstr ""

#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:434
msgid "The Workgroup field is empty!"
msgstr ""

#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:442
msgid "The AD administrator user field is empty!"
msgstr ""

#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:451
msgid "The AD administrator password field is empty!"
msgstr ""

#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:459
msgid "Can't connect to Active Directory server!"
msgstr ""

#: ../gecosws_config_assistant/view/ADSetupDataElemView.py:118
msgid ""
"Can't connect to Active Directory.\n"
"Please double-check all the fields"
msgstr ""

#: ../gecosws_config_assistant/view/ConnectWithGecosCCDialog.py:159
msgid "Disconnect from CC GECOS"
msgstr ""

#: ../gecosws_config_assistant/view/ConnectWithGecosCCDialog.py:161
msgid "Connect to CC GECOS"
msgstr ""

#: ../gecosws_config_assistant/view/GecosCCSetupProcessView.py:51
msgid "GECOS CC connection process"
msgstr ""

#: ../gecosws_config_assistant/view/GecosCCSetupProcessView.py:64
msgid "Check GECOS credentials"
msgstr ""

#: ../gecosws_config_assistant/view/GecosCCSetupProcessView.py:67
#: ../gecosws_config_assistant/view/GecosCCSetupProcessView.py:74
#: ../gecosws_config_assistant/view/GecosCCSetupProcessView.py:81
#: ../gecosws_config_assistant/view/GecosCCSetupProcessView.py:88
#: ../gecosws_config_assistant/view/GecosCCSetupProcessView.py:95
#: ../gecosws_config_assistant/view/GecosCCSetupProcessView.py:102
msgid "PENDING"
msgstr ""

#: ../gecosws_config_assistant/view/GecosCCSetupProcessView.py:71
msgid "Check workstation data"
msgstr ""

#: ../gecosws_config_assistant/view/GecosCCSetupProcessView.py:78
msgid "Get chef certificate"
msgstr ""

#: ../gecosws_config_assistant/view/GecosCCSetupProcessView.py:92
msgid "Register in GECOS"
msgstr ""

#: ../gecosws_config_assistant/view/GecosCCSetupProcessView.py:99
msgid "Clean setup data"
msgstr ""

#: ../gecosws_config_assistant/view/GecosCCSetupProcessView.py:109
#: ../gecosws_config_assistant/view/LocalUserElemView.py:121
#: ../gecosws_config_assistant/view/SystemStatusElemView.py:83
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:114
msgid "Accept"
msgstr ""

#: ../gecosws_config_assistant/view/LocalUserElemDialog.py:84
#: ../gecosws_config_assistant/view/LocalUserElemView.py:133
msgid "Modifiy local user"
msgstr ""

#: ../gecosws_config_assistant/view/LocalUserElemDialog.py:90
#: ../gecosws_config_assistant/view/LocalUserElemView.py:65
#: ../gecosws_config_assistant/view/LocalUserElemView.py:141
msgid "Add local user"
msgstr ""

#: ../gecosws_config_assistant/view/LocalUserElemDialog.py:122
#: ../gecosws_config_assistant/view/LocalUserElemView.py:155
msgid "The password confirmation field is empty!"
msgstr ""

#: ../gecosws_config_assistant/view/LocalUserElemDialog.py:130
#: ../gecosws_config_assistant/view/LocalUserElemView.py:163
msgid "The password confirmation is different from password"
msgstr ""

#: ../gecosws_config_assistant/view/LocalUserElemView.py:79
msgid "Name:"
msgstr ""

#: ../gecosws_config_assistant/view/LocalUserElemView.py:88
#: ../gecosws_config_assistant/view/SystemStatusElemDialog.py:117
#: ../gecosws_config_assistant/view/SystemStatusElemView.py:121
msgid "Login:"
msgstr ""

#: ../gecosws_config_assistant/view/LocalUserElemView.py:98
#: ../gecosws_config_assistant/view/UserAuthDialog.py:281
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:163
msgid "Password:"
msgstr ""

#: ../gecosws_config_assistant/view/LocalUserElemView.py:107
msgid "Confirm:"
msgstr ""

#: ../gecosws_config_assistant/view/LocalUserElemView.py:116
msgid "Cancel"
msgstr ""

#: ../gecosws_config_assistant/view/LocalUserListView.py:62
msgid "Manage local users"
msgstr ""

#: ../gecosws_config_assistant/view/LocalUserListView.py:75
msgid "You can create, update or delete local users in this workstation."
msgstr ""

#: ../gecosws_config_assistant/view/LocalUserListView.py:78
msgid ""
"It isn't necessary to create here the users that are authenticated by "
"external services (LDAP, AD, ...)"
msgstr ""

#: ../gecosws_config_assistant/view/LocalUserListView.py:84
msgid "Please check default OEM users and change their passwords when needed:"
msgstr ""

#: ../gecosws_config_assistant/view/LocalUserListView.py:92
msgid "Login"
msgstr ""

#: ../gecosws_config_assistant/view/LocalUserListView.py:93
msgid "Name"
msgstr ""

#: ../gecosws_config_assistant/view/LocalUserListView.py:112
msgid "New"
msgstr ""

#: ../gecosws_config_assistant/view/LocalUserListView.py:117
msgid "Update"
msgstr ""

#: ../gecosws_config_assistant/view/LocalUserListView.py:122
msgid "Delete"
msgstr ""

#: ../gecosws_config_assistant/view/LocalUserListView.py:128
msgid "Go Back"
msgstr ""

#: ../gecosws_config_assistant/view/LogTerminalDialog.py:110
msgid "Log terminal"
msgstr ""

#: ../gecosws_config_assistant/view/MainWindow.py:168
msgid "Link with GECOS server"
msgstr ""

#: ../gecosws_config_assistant/view/MainWindow.py:170
msgid ""
"You must link your workstation with a GECOS server to be \n"
"able to manage this workstation in a centralized way"
msgstr ""

#: ../gecosws_config_assistant/view/MainWindow.py:178
msgid "Setup user authentication method"
msgstr ""

#: ../gecosws_config_assistant/view/MainWindow.py:180
msgid ""
"You must setup the user authentication method to either: internal users, "
"LDAP or Active Directory"
msgstr ""

#: ../gecosws_config_assistant/view/MainWindow.py:356
msgid "Unlink"
msgstr ""

#: ../gecosws_config_assistant/view/NTPServerElemView.py:115
msgid ""
"Can't connect with NTP server.\n"
"Please double-check the NTP server address"
msgstr ""

#: ../gecosws_config_assistant/view/NTPServerElemView.py:118
msgid "NTP server connection successful"
msgstr ""

#: ../gecosws_config_assistant/view/SystemStatusElemDialog.py:87
#: ../gecosws_config_assistant/view/SystemStatusElemView.py:65
msgid "System status"
msgstr ""

#: ../gecosws_config_assistant/view/SystemStatusElemDialog.py:92
#: ../gecosws_config_assistant/view/SystemStatusElemDialog.py:94
#: ../gecosws_config_assistant/view/SystemStatusElemView.py:96
#: ../gecosws_config_assistant/view/SystemStatusElemView.py:98
msgid "Assistant version: "
msgstr ""

#: ../gecosws_config_assistant/view/SystemStatusElemDialog.py:94
#: ../gecosws_config_assistant/view/SystemStatusElemView.py:98
msgid "UNKNOWN VERSION"
msgstr ""

#: ../gecosws_config_assistant/view/SystemStatusElemDialog.py:99
#: ../gecosws_config_assistant/view/SystemStatusElemView.py:103
msgid "Workstation name: "
msgstr ""

#: ../gecosws_config_assistant/view/SystemStatusElemDialog.py:104
#: ../gecosws_config_assistant/view/SystemStatusElemView.py:108
msgid "Time server: "
msgstr ""

#: ../gecosws_config_assistant/view/SystemStatusElemDialog.py:107
#: ../gecosws_config_assistant/view/SystemStatusElemView.py:111
msgid "Network interfaces: "
msgstr ""

#: ../gecosws_config_assistant/view/SystemStatusElemDialog.py:113
#: ../gecosws_config_assistant/view/SystemStatusElemView.py:117
msgid "GECOS Control Center connection data: "
msgstr ""

#: ../gecosws_config_assistant/view/SystemStatusElemDialog.py:116
#: ../gecosws_config_assistant/view/SystemStatusElemView.py:120
msgid "Server URL:"
msgstr ""

#: ../gecosws_config_assistant/view/SystemStatusElemDialog.py:120
#: ../gecosws_config_assistant/view/SystemStatusElemView.py:124
msgid "Local users: "
msgstr ""

#: ../gecosws_config_assistant/view/SystemStatusElemDialog.py:127
#: ../gecosws_config_assistant/view/SystemStatusElemView.py:131
msgid "User authentication method: "
msgstr ""

#: ../gecosws_config_assistant/view/SystemStatusElemDialog.py:130
#: ../gecosws_config_assistant/view/SystemStatusElemView.py:134
msgid "Method:"
msgstr ""

#: ../gecosws_config_assistant/view/SystemStatusElemDialog.py:133
#: ../gecosws_config_assistant/view/SystemStatusElemView.py:137
#: ../gecosws_config_assistant/view/UserAuthDialog.py:246
#: ../gecosws_config_assistant/view/UserAuthDialog.py:278
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:140
msgid "Domain:"
msgstr ""

#: ../gecosws_config_assistant/view/SystemStatusElemDialog.py:134
#: ../gecosws_config_assistant/view/SystemStatusElemView.py:138
#: ../gecosws_config_assistant/view/UserAuthDialog.py:247
#: ../gecosws_config_assistant/view/UserAuthDialog.py:279
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:147
msgid "Workgroup:"
msgstr ""

#: ../gecosws_config_assistant/view/SystemStatusElemDialog.py:137
#: ../gecosws_config_assistant/view/SystemStatusElemView.py:141
msgid "Server URI:"
msgstr ""

#: ../gecosws_config_assistant/view/SystemStatusElemDialog.py:138
#: ../gecosws_config_assistant/view/SystemStatusElemView.py:142
#: ../gecosws_config_assistant/view/UserAuthDialog.py:215
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:219
msgid "Users base DN:"
msgstr ""

#: ../gecosws_config_assistant/view/SystemStatusElemDialog.py:139
#: ../gecosws_config_assistant/view/SystemStatusElemView.py:143
msgid "Groups base DN:"
msgstr ""

#: ../gecosws_config_assistant/view/SystemStatusElemDialog.py:144
#: ../gecosws_config_assistant/view/SystemStatusElemView.py:148
msgid "No status data!"
msgstr ""

#: ../gecosws_config_assistant/view/UserAuthDialog.py:211
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:207
msgid "Please fill the data to setup the LDAP authentication method."
msgstr ""

#: ../gecosws_config_assistant/view/UserAuthDialog.py:214
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:212
msgid "LDAP server URI:"
msgstr ""

#: ../gecosws_config_assistant/view/UserAuthDialog.py:216
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:226
msgid "Groups base DN (optional):"
msgstr ""

#: ../gecosws_config_assistant/view/UserAuthDialog.py:217
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:233
msgid "Bind user DN (optional):"
msgstr ""

#: ../gecosws_config_assistant/view/UserAuthDialog.py:218
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:241
msgid "Bind user password (optional):"
msgstr ""

#: ../gecosws_config_assistant/view/UserAuthDialog.py:243
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:136
msgid ""
"Please fill the data to setup the Active Directory authentication method."
msgstr ""

#: ../gecosws_config_assistant/view/UserAuthDialog.py:248
msgid "(Active Directory) User:"
msgstr ""

#: ../gecosws_config_assistant/view/UserAuthDialog.py:249
msgid "(Active Directory) Password:"
msgstr ""

#: ../gecosws_config_assistant/view/UserAuthDialog.py:274
msgid ""
"Specific configuration data was loaded from GECOS server\n"
" (sssd.conf, krb5.conf, smb.conf and pam.conf)"
msgstr ""

#: ../gecosws_config_assistant/view/UserAuthDialog.py:280
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:154
msgid "User:"
msgstr ""

#: ../gecosws_config_assistant/view/UserAuthDialog.py:307
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:287
msgid ""
"There is no necessary data to setup the local users authentication method."
msgstr ""

#: ../gecosws_config_assistant/view/UserAuthDialog.py:408
#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:378
msgid "An error happened while saving the users authentication method!"
msgstr ""

#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:72
msgid "User authentication method"
msgstr ""

#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:85
msgid "The users of this workstation may authenticate by using"
msgstr ""

#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:88
msgid "an external system like LDAP or Microsoft Active Directory."
msgstr ""

#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:91
msgid "Also, they can be authenticated by using local users of this O.S."
msgstr ""

#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:95
msgid "Authentication type:"
msgstr ""

#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:109
msgid "Setup"
msgstr ""

#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:125
msgid "Active Directory authentication"
msgstr ""

#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:196
msgid "LDAP authentication"
msgstr ""

#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:276
msgid "Local users authentication"
msgstr ""

#: ../gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:377
msgid "Error saving authentication method"
msgstr ""
